from playwright.sync_api import sync_playwright

import json

from pathlib import Path

from lib.smart_ai import patch_page_with_smartai

from pages.contact1_page_methods import *

from pages.contact2_page_methods import *

from pages.contact3_page_methods import *

from pages.contact_page_methods import *

from pages.dashbord_page_methods import *

from pages.detail2_page_methods import *

from pages.detail_page_methods import *

from pages.sandes_page_methods import *

def test_positive_create_contact(page):
    page.goto("https://thdynamics365sandbox.crm4.dynamics.com/main.aspx")
    verify_dynamics_365_visible(page)
    click_customer_service(page)
    verify_customer_service_visible(page)
    click_contacts(page)
    click_new(page)
    verify_new_contact_visible(page)
    select_salutation(page, "Mr.")
    assert_select_salutation(page, "Mr.")
    enter_first_name(page, "Jamie")
    assert_enter_first_name(page, "Jamie")
    enter_last_name(page, "Rivera")
    assert_enter_last_name(page, "Rivera")
    enter_job_title(page, "Support Analyst")
    assert_enter_job_title(page, "Support Analyst")
    enter_account_name(page, "akash")
    assert_enter_account_name(page, "akash")
    select_role(page, "Employee")
    assert_select_role(page, "Employee")
    enter_reports_to(page, "govind n")
    assert_enter_reports_to(page, "govind n")
    enter_department(page, "Customer Service")
    assert_enter_department(page, "Customer Service")
    select_primary_time_zone(page, "(GMT-05:00) Haiti")
    assert_select_primary_time_zone(page, "(GMT-05:00) Haiti")
    enter_email(page, "jamie.rivera@example.com")
    assert_enter_email(page, "jamie.rivera@example.com")
    enter_business_phone(page, "+91 40 5555 0188")
    assert_enter_business_phone(page, "+91 40 5555 0188")
    enter_mobile_phone(page, "+91 40 5555 0123")
    assert_enter_mobile_phone(page, "+91 40 5555 0123")
    enter_fax(page, "+91 40 5555 0199")
    assert_enter_fax(page, "+91 40 5555 0199")
    select_lead_source(page, "Web")
    assert_select_lead_source(page, "Web")
    select_preferred_method_of_contact(page, "Email")
    assert_select_preferred_method_of_contact(page, "Email")
    enter_hobbies_and_interests(page, "Hiking; Reading")
    assert_enter_hobbies_and_interests(page, "Hiking; Reading")
    enter_assistant(page, "Casey Morgan")
    assert_enter_assistant(page, "Casey Morgan")
    enter_assistant_phone(page, "+91 40 5555 0147")
    assert_enter_assistant_phone(page, "+91 40 5555 0147")
    enter_home_phone(page, "+91 64 5555 9373")
    assert_enter_home_phone(page, "+91 64 5555 9373")
    enter_address_1_street_1(page, "12 Hitech City Rd")
    assert_enter_address_1_street_1(page, "12 Hitech City Rd")
    enter_address_1_city(page, "Hyderabad")
    assert_enter_address_1_city(page, "Hyderabad")
    enter_address_1_state_province(page, "Telangana")
    assert_enter_address_1_state_province(page, "Telangana")
    enter_address_1_country_region(page, "India")
    assert_enter_address_1_country_region(page, "India")
    enter_address_1_zip_postal_code(page, "500081")
    assert_enter_address_1_zip_postal_code(page, "500081")
    enter_address_1_phone(page, "+91 40 5555 0100")
    assert_enter_address_1_phone(page, "+91 40 5555 0100")
    enter_address_2_street_1(page, "44 MG Road")
    assert_enter_address_2_street_1(page, "44 MG Road")
    enter_address_2_city(page, "Bengaluru")
    assert_enter_address_2_city(page, "Bengaluru")
    enter_address_2_state_province(page, "Karnataka")
    assert_enter_address_2_state_province(page, "Karnataka")
    enter_address_2_country_region(page, "India")
    assert_enter_address_2_country_region(page, "India")
    enter_address_2_zip_postal_code(page, "560001")
    assert_enter_address_2_zip_postal_code(page, "560001")
    enter_address_2_phone(page, "+91 80 5555 0107")
    assert_enter_address_2_phone(page, "+91 80 5555 0107")
    enter_company(page, "govind n")
    assert_enter_company(page, "govind n")
    click_details(page)
    select_gender(page, "Male")
    assert_select_gender(page, "Male")
    select_marital_status(page, "Married")
    assert_select_marital_status(page, "Married")
    enter_spouse_partner_name(page, "Alex Rivera")
    assert_enter_spouse_partner_name(page, "Alex Rivera")
    enter_credit_limit(page, "100000")
    assert_enter_credit_limit(page, "100000")
    select_credit_hold(page, "No")
    assert_select_credit_hold(page, "No")
    select_payment_terms(page, "Net 30")
    assert_select_payment_terms(page, "Net 30")
    select_shipping_method(page, "DHL")
    assert_select_shipping_method(page, "DHL")
    select_freight_terms(page, "FOB")
    assert_select_freight_terms(page, "FOB")
    enter_originating_lead(page, "Arjun A")
    assert_enter_originating_lead(page, "Arjun A")
    select_marketing_materials(page, "Send")
    assert_select_marketing_materials(page, "Send")
    click_save_close(page)

def test_negative_create_contact(page):
    page.goto("https://thdynamics365sandbox.crm4.dynamics.com/main.aspx")
    verify_dynamics_365_visible(page)
    click_customer_service(page)
    verify_customer_service_visible(page)
    click_contacts(page)
    click_new(page)
    verify_new_contact_visible(page)
    select_salutation(page, "Mr.")
    assert_select_salutation(page, "Mr.")
    enter_first_name(page, "")  # Missing first name
    enter_last_name(page, "Rivera")
    assert_enter_last_name(page, "Rivera")
    enter_job_title(page, "Support Analyst")
    assert_enter_job_title(page, "Support Analyst")
    enter_account_name(page, "akash")
    assert_enter_account_name(page, "akash")
    select_role(page, "Employee")
    assert_select_role(page, "Employee")
    enter_reports_to(page, "govind n")
    assert_enter_reports_to(page, "govind n")
    enter_department(page, "Customer Service")
    assert_enter_department(page, "Customer Service")
    select_primary_time_zone(page, "(GMT-05:00) Haiti")
    assert_select_primary_time_zone(page, "(GMT-05:00) Haiti")
    enter_email(page, "jamie.rivera@example.com")
    assert_enter_email(page, "jamie.rivera@example.com")
    enter_business_phone(page, "+91 40 5555 0188")
    assert_enter_business_phone(page, "+91 40 5555 0188")
    enter_mobile_phone(page, "+91 40 5555 0123")
    assert_enter_mobile_phone(page, "+91 40 5555 0123")
    enter_fax(page, "+91 40 5555 0199")
    assert_enter_fax(page, "+91 40 5555 0199")
    select_lead_source(page, "Web")
    assert_select_lead_source(page, "Web")
    select_preferred_method_of_contact(page, "Email")
    assert_select_preferred_method_of_contact(page, "Email")
    enter_hobbies_and_interests(page, "Hiking; Reading")
    assert_enter_hobbies_and_interests(page, "Hiking; Reading")
    enter_assistant(page, "Casey Morgan")
    assert_enter_assistant(page, "Casey Morgan")
    enter_assistant_phone(page, "+91 40 5555 0147")
    assert_enter_assistant_phone(page, "+91 40 5555 0147")
    enter_home_phone(page, "+91 64 5555 9373")
    assert_enter_home_phone(page, "+91 64 5555 9373")
    enter_address_1_street_1(page, "12 Hitech City Rd")
    assert_enter_address_1_street_1(page, "12 Hitech City Rd")
    enter_address_1_city(page, "Hyderabad")
    assert_enter_address_1_city(page, "Hyderabad")
    enter_address_1_state_province(page, "Telangana")
    assert_enter_address_1_state_province(page, "Telangana")
    enter_address_1_country_region(page, "India")
    assert_enter_address_1_country_region(page, "India")
    enter_address_1_zip_postal_code(page, "500081")
    assert_enter_address_1_zip_postal_code(page, "500081")
    enter_address_1_phone(page, "+91 40 5555 0100")
    assert_enter_address_1_phone(page, "+91 40 5555 0100")
    enter_address_2_street_1(page, "44 MG Road")
    assert_enter_address_2_street_1(page, "44 MG Road")
    enter_address_2_city(page, "Bengaluru")
    assert_enter_address_2_city(page, "Bengaluru")
    enter_address_2_state_province(page, "Karnataka")
    assert_enter_address_2_state_province(page, "Karnataka")
    enter_address_2_country_region(page, "India")
    assert_enter_address_2_country_region(page, "India")
    enter_address_2_zip_postal_code(page, "560001")
    assert_enter_address_2_zip_postal_code(page, "560001")
    enter_address_2_phone(page, "+91 80 5555 0107")
    assert_enter_address_2_phone(page, "+91 80 5555 0107")
    enter_company(page, "govind n")
    assert_enter_company(page, "govind n")
    click_details(page)
    select_gender(page, "Male")
    assert_select_gender(page, "Male")
    select_marital_status(page, "Married")
    assert_select_marital_status(page, "Married")
    enter_spouse_partner_name(page, "Alex Rivera")
    assert_enter_spouse_partner_name(page, "Alex Rivera")
    enter_credit_limit(page, "100000")
    assert_enter_credit_limit(page, "100000")
    select_credit_hold(page, "No")
    assert_select_credit_hold(page, "No")
    select_payment_terms(page, "Net 30")
    assert_select_payment_terms(page, "Net 30")
    select_shipping_method(page, "DHL")
    assert_select_shipping_method(page, "DHL")
    select_freight_terms(page, "FOB")
    assert_select_freight_terms(page, "FOB")
    enter_originating_lead(page, "Arjun A")
    assert_enter_originating_lead(page, "Arjun A")
    select_marketing_materials(page, "Send")
    assert_select_marketing_materials(page, "Send")
    click_save_close(page)

def test_edge_create_contact(page):
    page.goto("https://thdynamics365sandbox.crm4.dynamics.com/main.aspx")
    verify_dynamics_365_visible(page)
    click_customer_service(page)
    verify_customer_service_visible(page)
    click_contacts(page)
    click_new(page)
    verify_new_contact_visible(page)
    select_salutation(page, "Mr.")
    assert_select_salutation(page, "Mr.")
    enter_first_name(page, "J" * 256)  # Very long first name
    enter_last_name(page, "Rivera")
    assert_enter_last_name(page, "Rivera")
    enter_job_title(page, "Support Analyst")
    assert_enter_job_title(page, "Support Analyst")
    enter_account_name(page, "akash")
    assert_enter_account_name(page, "akash")
    select_role(page, "Employee")
    assert_select_role(page, "Employee")
    enter_reports_to(page, "govind n")
    assert_enter_reports_to(page, "govind n")
    enter_department(page, "Customer Service")
    assert_enter_department(page, "Customer Service")
    select_primary_time_zone(page, "(GMT-05:00) Haiti")
    assert_select_primary_time_zone(page, "(GMT-05:00) Haiti")
    enter_email(page, "jamie.rivera@example.com")
    assert_enter_email(page, "jamie.rivera@example.com")
    enter_business_phone(page, "+91 40 5555 0188")
    assert_enter_business_phone(page, "+91 40 5555 0188")
    enter_mobile_phone(page, "+91 40 5555 0123")
    assert_enter_mobile_phone(page, "+91 40 5555 0123")
    enter_fax(page, "+91 40 5555 0199")
    assert_enter_fax(page, "+91 40 5555 0199")
    select_lead_source(page, "Web")
    assert_select_lead_source(page, "Web")
    select_preferred_method_of_contact(page, "Email")
    assert_select_preferred_method_of_contact(page, "Email")
    enter_hobbies_and_interests(page, "Hiking; Reading")
    assert_enter_hobbies_and_interests(page, "Hiking; Reading")
    enter_assistant(page, "Casey Morgan")
    assert_enter_assistant(page, "Casey Morgan")
    enter_assistant_phone(page, "+91 40 5555 0147")
    assert_enter_assistant_phone(page, "+91 40 5555 0147")
    enter_home_phone(page, "+91 64 5555 9373")
    assert_enter_home_phone(page, "+91 64 5555 9373")
    enter_address_1_street_1(page, "12 Hitech City Rd")
    assert_enter_address_1_street_1(page, "12 Hitech City Rd")
    enter_address_1_city(page, "Hyderabad")
    assert_enter_address_1_city(page, "Hyderabad")
    enter_address_1_state_province(page, "Telangana")
    assert_enter_address_1_state_province(page, "Telangana")
    enter_address_1_country_region(page, "India")
    assert_enter_address_1_country_region(page, "India")
    enter_address_1_zip_postal_code(page, "500081")
    assert_enter_address_1_zip_postal_code(page, "500081")
    enter_address_1_phone(page, "+91 40 5555 0100")
    assert_enter_address_1_phone(page, "+91 40 5555 0100")
    enter_address_2_street_1(page, "44 MG Road")
    assert_enter_address_2_street_1(page, "44 MG Road")
    enter_address_2_city(page, "Bengaluru")
    assert_enter_address_2_city(page, "Bengaluru")
    enter_address_2_state_province(page, "Karnataka")
    assert_enter_address_2_state_province(page, "Karnataka")
    enter_address_2_country_region(page, "India")
    assert_enter_address_2_country_region(page, "India")
    enter_address_2_zip_postal_code(page, "560001")
    assert_enter_address_2_zip_postal_code(page, "560001")
    enter_address_2_phone(page, "+91 80 5555 0107")
    assert_enter_address_2_phone(page, "+91 80 5555 0107")
    enter_company(page, "govind n")
    assert_enter_company(page, "govind n")
    click_details(page)
    select_gender(page, "Male")
    assert_select_gender(page, "Male")
    select_marital_status(page, "Married")
    assert_select_marital_status(page, "Married")
    enter_spouse_partner_name(page, "Alex Rivera")
    assert_enter_spouse_partner_name(page, "Alex Rivera")
    enter_credit_limit(page, "100000")
    assert_enter_credit_limit(page, "100000")
    select_credit_hold(page, "No")
    assert_select_credit_hold(page, "No")
    select_payment_terms(page, "Net 30")
    assert_select_payment_terms(page, "Net 30")
    select_shipping_method(page, "DHL")
    assert_select_shipping_method(page, "DHL")
    select_freight_terms(page, "FOB")
    assert_select_freight_terms(page, "FOB")
    enter_originating_lead(page, "Arjun A")
    assert_enter_originating_lead(page, "Arjun A")
    select_marketing_materials(page, "Send")
    assert_select_marketing_materials(page, "Send")
    click_save_close(page)