services:
  frontend:
    build:
      context: ./FRONTEND-NEW
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - testify-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - chromadb
    networks:
      - testify-net

    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: Testify-backend-logs
        awslogs-stream: Backend-Container
        awslogs-create-group: "true"

  chromadb:
    image: chromadb/chroma:1.0.12
    volumes:
      - chroma_data:/chroma/.chroma/index
    networks:
      - testify-net

volumes:
  chroma_data:

networks:
  testify-net:
    driver: bridge