services:
  frontend:
    build:
      context: ./frontend-demo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - chromadb
      - image_text_service # Add dependency on the new service
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
      - IMAGE_TEXT_SERVICE_URL=http://image_text_service:8002
      - CHROMA_DEBUG_SERVICE_URL=http://chroma_debug_service:8003
      - ENRICHMENT_SERVICE_URL=http://enrichment_service:8004
      - RAG_SERVICE_URL=http://rag_testcase_service:8005
      - TEST_GENERATION_SERVICE_URL=http://test_generation_service:8006
      - ORCHESTRATOR_SERVICE_URL=http://orchestrator_service:8007
      - PAGE_METHOD_GENERATION_SERVICE_URL=http://page_method_generation_service:8008
      - MANUAL_TESTCASE_GENERATION_SERVICE_URL=http://manual_testcase_generation_service:8009
      - TESTCASE_GENERATION_SERVICE_URL=http://testcase_generation_service:8010
      - MANUAL_METADATA_SERVICE_URL=http://manual_metadata_service:8011

  manual_metadata_service:
    build:
      context: ./microservices/manual_metadata_service
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  testcase_generation_service:
    build:
      context: ./microservices/testcase_generation_service
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  manual_testcase_generation_service:
    build:
      context: ./microservices/manual_testcase_generation_service
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  page_method_generation_service:
    build:
      context: ./microservices/page_method_generation_service
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    env_file:
      - .env
    depends_on:
      - chromadb
      - orchestrator_service
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
      - ORCHESTRATOR_SERVICE_URL=http://orchestrator_service:8007

  orchestrator_service:
    build:
      context: ./microservices/orchestrator_service
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    env_file:
      - .env

  image_text_service:
    build:
      context: ./microservices/image_text_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000
      - DATA_PATH=/app/data # Define DATA_PATH for the service

  test_generation_service:
    build:
      context: ./microservices/test_generation_service
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  rag_testcase_service:
    build:
      context: ./microservices/rag_testcase_service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    env_file:
      - .env

  enrichment_service:
    build:
      context: ./microservices/enrichment_service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  chroma_debug_service:
    build:
      context: ./microservices/chroma_debug_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index

volumes:
  chroma_data: