import logging
import os
import mimetypes
from pathlib import Path

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from sqlalchemy.exc import ProgrammingError
from sqlalchemy.orm import Session

from database.models import Project, ProjectAllureChart
from database.session import get_db
from .projects_api import _project_root, get_current_user, get_project_by_projectId
from database.models import User

router = APIRouter()
logger = logging.getLogger(__name__)

# The visualizations are generated by `allure_visualizer.py` in the repository root.
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_VISUALIZER_DIR = REPO_ROOT / "allure_reports"
VISUALIZER_ENV_VARS = (
    "VISUALIZER_OUTPUT_DIR",
    "ALLURE_OUTPUT_DIR",
    "SMARTAI_VISUALIZER_DIR",
)


def _auto_detect_allure_charts_dir(root: Path) -> Path | None:
    org_root = root / "backend" / "organizations"
    if not org_root.is_dir():
        return None

    best_candidate = None
    best_mtime = -1.0
    for account_dir in org_root.iterdir():
        if not account_dir.is_dir():
            continue
        for project_dir in account_dir.iterdir():
            if not project_dir.is_dir():
                continue
            candidate = project_dir / "generated_runs" / "src" / "allure_charts"
            if not candidate.is_dir():
                continue
            try:
                mtime = candidate.stat().st_mtime
            except (OSError, PermissionError):
                continue
            if mtime > best_mtime:
                best_mtime = mtime
                best_candidate = candidate

    return best_candidate


def _get_visualizer_dir() -> Path:
    """Resolve the directory where visualizer assets are written."""
    for var in VISUALIZER_ENV_VARS:
        configured = os.environ.get(var)
        if configured:
            return Path(configured).expanduser()
    auto_dir = _auto_detect_allure_charts_dir(REPO_ROOT)
    if auto_dir:
        return auto_dir
    return DEFAULT_VISUALIZER_DIR


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
ALLOWED_ASSET_EXTENSIONS = IMAGE_EXTENSIONS | {".html"}
INTERACTIVE_DASHBOARD = "interactive_charts.html"


def _ensure_visualizer_dir(directory: Path):
    if not directory.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Visualizer output directory not found: {directory}",
        )


def _dashboard_path(directory: Path) -> Path:
    return (directory / INTERACTIVE_DASHBOARD).resolve()


def _chart_asset_type(path: Path) -> Optional[str]:
    suffix = path.suffix.lower()
    if suffix in IMAGE_EXTENSIONS:
        return "image"
    if suffix == ".html":
        if path.name == INTERACTIVE_DASHBOARD:
            return "dashboard"
        return "interactive"
    return None


def _friendly_chart_label(chart_key: str) -> str:
    if chart_key.lower() == "interactive_charts":
        return "Interactive Dashboard"
    return chart_key.replace("_", " ").strip().title()


def _list_project_visualizations_from_disk(project: Project) -> dict:
    project_root = _project_root(project).resolve()
    charts_dir = (project_root / "generated_runs" / "src" / "allure_charts").resolve()
    if not charts_dir.is_dir():
        return {"project_id": project.id, "images": [], "interactive_charts": [], "interactive_dashboard": None}

    images = []
    interactive = []
    dashboard_url = None
    base_url = "/visualizer/projects"
    for asset in sorted(charts_dir.iterdir()):
        if not asset.is_file():
            continue
        asset_type = _chart_asset_type(asset)
        if not asset_type:
            continue
        relative_path = asset.relative_to(charts_dir).as_posix()
        media_type_guess, _ = mimetypes.guess_type(str(asset))
        entry = {
            "id": None,
            "name": asset.stem,
            "label": _friendly_chart_label(asset.stem),
            "url": f"{base_url}/{project.id}/assets/{relative_path}",
            "media_type": media_type_guess or "application/octet-stream",
            "asset_type": asset_type,
        }
        if asset_type == "image":
            images.append(entry)
        elif asset_type == "interactive":
            interactive.append(entry)
        elif asset_type == "dashboard" and dashboard_url is None:
            dashboard_url = entry["url"]

    return {
        "project_id": project.id,
        "images": images,
        "interactive_charts": interactive,
        "interactive_dashboard": dashboard_url,
    }


@router.get("/images")
def list_visualizations(
    project_id: int = Query(..., description="Project ID to scope the charts to"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return metadata for every image generated by the Allure visualizer."""
    return _list_project_visualizations(project_id, db, current_user)


def _list_project_visualizations(project_id: int, db: Session, current_user: User) -> dict:
    project = get_project_by_projectId(db, project_id, current_user)
    try:
        records = (
            db.query(ProjectAllureChart)
            .filter(ProjectAllureChart.project_id == project_id)
            .order_by(ProjectAllureChart.asset_type.asc(), ProjectAllureChart.chart_key.asc())
            .all()
        )
    except ProgrammingError as exc:
        message = str(exc).lower()
        if "project_allure_charts" in message:
            logger.warning(
                "project_allure_charts table missing for project %s, falling back to disk for assets",
                project_id,
            )
            return _list_project_visualizations_from_disk(project)
        raise
    if not records:
        return _list_project_visualizations_from_disk(project)
    images = []
    interactive = []
    dashboard_url = None
    base_url = "/visualizer/projects"
    for record in records:
        entry = {
            "id": record.id,
            "name": record.chart_key,
            "label": record.label or record.chart_key,
            "url": f"{base_url}/{project_id}/assets/{record.id}",
            "media_type": record.media_type,
            "asset_type": record.asset_type,
        }
        if record.asset_type == "image":
            images.append(entry)
        elif record.asset_type == "interactive":
            interactive.append(entry)
        elif record.asset_type == "dashboard" and dashboard_url is None:
            dashboard_url = entry["url"]
    if not interactive and dashboard_url is None:
        return _list_project_visualizations_from_disk(project)
    return {
        "project_id": project_id,
        "images": images,
        "interactive_charts": interactive,
        "interactive_dashboard": dashboard_url,
    }


@router.get("/projects/{project_id}/assets")
def list_project_assets(
    project_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Expose the current project's Allure chart assets."""
    return _list_project_visualizations(project_id, db, current_user)


def _project_asset_candidate(project, record):
    project_root = _project_root(project).resolve()
    candidate = (project_root / record.relative_path).resolve()
    if not str(candidate).startswith(str(project_root)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not candidate.exists() or not candidate.is_file():
        raise HTTPException(status_code=404, detail="Visualization file not found")
    return candidate


@router.get("/projects/{project_id}/assets/{asset_path:path}")
def get_project_asset(
    project_id: int,
    asset_path: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Serve an Allure chart asset that belongs to a specific project."""
    project = get_project_by_projectId(db, project_id, current_user)

    resolved_candidate = None
    media_type = "application/octet-stream"

    if asset_path.isdigit():
        record = (
            db.query(ProjectAllureChart)
            .filter(
                ProjectAllureChart.id == int(asset_path),
                ProjectAllureChart.project_id == project_id,
            )
            .first()
        )

        if not record:
            raise HTTPException(status_code=404, detail="Visualization not found")
        resolved_candidate = _project_asset_candidate(project, record)
        media_type = record.media_type or media_type
    else:
        charts_dir = (_project_root(project) / "generated_runs" / "src" / "allure_charts").resolve()
        normalized_path = asset_path.lstrip("/")
        assets_prefix = "assets/"
        while normalized_path.startswith(assets_prefix):
            normalized_path = normalized_path[len(assets_prefix):]
        candidate = (charts_dir / normalized_path).resolve()
        if not str(candidate).startswith(str(charts_dir)):
            raise HTTPException(status_code=403, detail="Forbidden")
        if not candidate.exists() or not candidate.is_file():
            raise HTTPException(status_code=404, detail="Visualization file not found")
        resolved_candidate = candidate
        media_type_guess, _ = mimetypes.guess_type(str(candidate))
        if media_type_guess:
            media_type = media_type_guess

    return FileResponse(resolved_candidate, media_type=media_type)


@router.get("/assets/{image_name}")
def get_visualization_asset(
    image_name: str,
    project_id: int = Query(..., description="Project ID to scope the asset to"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Serve the raw image file for the visualizer output."""
    project = get_project_by_projectId(db, project_id, current_user)
    charts_dir = (_project_root(project) / "generated_runs" / "src" / "allure_charts").resolve()
    candidate = (charts_dir / image_name).resolve()
    if not str(candidate).startswith(str(charts_dir)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not candidate.exists() or not candidate.is_file():
        raise HTTPException(status_code=404, detail="Visualization not found")
    if candidate.suffix.lower() not in ALLOWED_ASSET_EXTENSIONS:
        raise HTTPException(status_code=403, detail="Visualization type not allowed")
    media_type, _ = mimetypes.guess_type(str(candidate))
    return FileResponse(candidate, media_type=media_type or "application/octet-stream")


@router.get("/dashboard")
def get_interactive_dashboard(
    project_id: int = Query(..., description="Project ID to scope the dashboard to"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Serve the generated interactive HTML dashboard if available."""
    project = get_project_by_projectId(db, project_id, current_user)
    charts_dir = (_project_root(project) / "generated_runs" / "src" / "allure_charts").resolve()
    dashboard = (charts_dir / INTERACTIVE_DASHBOARD).resolve()
    if not str(dashboard).startswith(str(charts_dir)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not dashboard.exists() or not dashboard.is_file():
        raise HTTPException(status_code=404, detail="Interactive dashboard not found")
    return FileResponse(dashboard, media_type="text/html")
