import os
import mimetypes
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()

# The visualizations are generated by `allure_visualizer.py` in the repository root.
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_VISUALIZER_DIR = REPO_ROOT / "allure_reports"
VISUALIZER_ENV_VARS = (
    "VISUALIZER_OUTPUT_DIR",
    "ALLURE_OUTPUT_DIR",
    "SMARTAI_VISUALIZER_DIR",
)


def _auto_detect_allure_charts_dir(root: Path) -> Path | None:
    org_root = root / "backend" / "organizations"
    if not org_root.is_dir():
        return None

    best_candidate = None
    best_mtime = -1.0
    for account_dir in org_root.iterdir():
        if not account_dir.is_dir():
            continue
        for project_dir in account_dir.iterdir():
            if not project_dir.is_dir():
                continue
            candidate = project_dir / "generated_runs" / "src" / "allure_charts"
            if not candidate.is_dir():
                continue
            try:
                mtime = candidate.stat().st_mtime
            except (OSError, PermissionError):
                continue
            if mtime > best_mtime:
                best_mtime = mtime
                best_candidate = candidate

    return best_candidate


def _get_visualizer_dir() -> Path:
    """Resolve the directory where visualizer assets are written."""
    for var in VISUALIZER_ENV_VARS:
        configured = os.environ.get(var)
        if configured:
            return Path(configured).expanduser()
    auto_dir = _auto_detect_allure_charts_dir(REPO_ROOT)
    if auto_dir:
        return auto_dir
    return DEFAULT_VISUALIZER_DIR


VISUALIZER_DIR = _get_visualizer_dir()
VISUALIZER_DIR_RESOLVED = VISUALIZER_DIR.resolve()
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
ALLOWED_ASSET_EXTENSIONS = IMAGE_EXTENSIONS | {".html"}
INTERACTIVE_DASHBOARD = "interactive_charts.html"


def _ensure_visualizer_dir():
    if not VISUALIZER_DIR.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Visualizer output directory not found: {VISUALIZER_DIR}",
        )


def _dashboard_path() -> Path:
    return (VISUALIZER_DIR / INTERACTIVE_DASHBOARD).resolve()


@router.get("/images")
def list_visualizations():
    """Return metadata for every image generated by the Allure visualizer."""
    _ensure_visualizer_dir()
    images = [
        {"name": p.name, "url": f"/visualizer/assets/{p.name}"}
        for p in sorted(VISUALIZER_DIR.iterdir())
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    ]
    dashboard = _dashboard_path()
    interactive_available = dashboard.exists() and str(dashboard).startswith(str(VISUALIZER_DIR_RESOLVED))
    return {
        "images": images,
        "interactive_dashboard": "/visualizer/dashboard" if interactive_available else None,
    }


@router.get("/assets/{image_name}")
def get_visualization_asset(image_name: str):
    """Serve the raw image file for the visualizer output."""
    _ensure_visualizer_dir()
    candidate = (VISUALIZER_DIR / image_name).resolve()
    if not str(candidate).startswith(str(VISUALIZER_DIR_RESOLVED)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not candidate.exists() or not candidate.is_file():
        raise HTTPException(status_code=404, detail="Visualization not found")
    if candidate.suffix.lower() not in ALLOWED_ASSET_EXTENSIONS:
        raise HTTPException(status_code=403, detail="Visualization type not allowed")

    media_type, _ = mimetypes.guess_type(str(candidate))
    return FileResponse(candidate, media_type=media_type or "application/octet-stream")


@router.get("/dashboard")
def get_interactive_dashboard():
    """Serve the generated interactive HTML dashboard if available."""
    _ensure_visualizer_dir()
    dashboard = _dashboard_path()
    if not str(dashboard).startswith(str(VISUALIZER_DIR_RESOLVED)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not dashboard.exists() or not dashboard.is_file():
        raise HTTPException(status_code=404, detail="Interactive dashboard not found")
    return FileResponse(dashboard, media_type="text/html")
