import logging
import os
import mimetypes
from pathlib import Path

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from database.models import Project, ProjectAllureChart
from database.session import get_db, get_db_optional
from utils.project_context import current_project_id

from .projects_api import _project_root

router = APIRouter()
logger = logging.getLogger(__name__)

# The visualizations are generated by `allure_visualizer.py` in the repository root.
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_VISUALIZER_DIR = REPO_ROOT / "allure_reports"
VISUALIZER_ENV_VARS = (
    "VISUALIZER_OUTPUT_DIR",
    "ALLURE_OUTPUT_DIR",
    "SMARTAI_VISUALIZER_DIR",
)


def _auto_detect_allure_charts_dir(root: Path) -> Path | None:
    org_root = root / "backend" / "organizations"
    if not org_root.is_dir():
        return None

    best_candidate = None
    best_mtime = -1.0
    for account_dir in org_root.iterdir():
        if not account_dir.is_dir():
            continue
        for project_dir in account_dir.iterdir():
            if not project_dir.is_dir():
                continue
            candidate = project_dir / "generated_runs" / "src" / "allure_charts"
            if not candidate.is_dir():
                continue
            try:
                mtime = candidate.stat().st_mtime
            except (OSError, PermissionError):
                continue
            if mtime > best_mtime:
                best_mtime = mtime
                best_candidate = candidate

    return best_candidate


def _get_visualizer_dir() -> Path:
    """Resolve the directory where visualizer assets are written."""
    for var in VISUALIZER_ENV_VARS:
        configured = os.environ.get(var)
        if configured:
            return Path(configured).expanduser()
    auto_dir = _auto_detect_allure_charts_dir(REPO_ROOT)
    if auto_dir:
        return auto_dir
    return DEFAULT_VISUALIZER_DIR


VISUALIZER_DIR = _get_visualizer_dir()
VISUALIZER_DIR_RESOLVED = VISUALIZER_DIR.resolve()
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
ALLOWED_ASSET_EXTENSIONS = IMAGE_EXTENSIONS | {".html"}
INTERACTIVE_DASHBOARD = "interactive_charts.html"


def _ensure_visualizer_dir():
    if not VISUALIZER_DIR.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Visualizer output directory not found: {VISUALIZER_DIR}",
        )


def _dashboard_path() -> Path:
    return (VISUALIZER_DIR / INTERACTIVE_DASHBOARD).resolve()


@router.get("/images")
def list_visualizations(
    project_id: Optional[int] = Query(None, description="Project ID to scope the charts to"),
    db: Optional[Session] = Depends(get_db_optional),
):
    """Return metadata for every image generated by the Allure visualizer."""
    target_project_id = project_id or current_project_id()
    if target_project_id:
        if db:
            try:
                return _list_project_visualizations(target_project_id, db)
            except HTTPException:
                raise
            except Exception:
                logger.exception(
                    "Failed to load visualizations for project %s, falling back to disk assets",
                    target_project_id,
                )
        else:
            logger.warning(
                "Database session unavailable while listing visualizations for project %s",
                target_project_id,
            )

    _ensure_visualizer_dir()
    images = [
        {"name": p.name, "url": f"/visualizer/assets/{p.name}"}
        for p in sorted(VISUALIZER_DIR.iterdir())
        if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS
    ]
    dashboard = _dashboard_path()
    interactive_available = dashboard.exists() and str(dashboard).startswith(str(VISUALIZER_DIR_RESOLVED))
    return {
        "images": images,
        "interactive_dashboard": "/visualizer/dashboard" if interactive_available else None,
    }


def _list_project_visualizations(project_id: int, db: Session) -> dict:
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail=f"Project with id '{project_id}' not found")
    records = (
        db.query(ProjectAllureChart)
        .filter(ProjectAllureChart.project_id == project_id)
        .order_by(ProjectAllureChart.asset_type.asc(), ProjectAllureChart.chart_key.asc())
        .all()
    )
    images = []
    interactive = []
    dashboard_url = None
    base_url = "/visualizer/projects"
    for record in records:
        entry = {
            "id": record.id,
            "name": record.chart_key,
            "label": record.label or record.chart_key,
            "url": f"{base_url}/{project_id}/assets/{record.id}",
            "media_type": record.media_type,
            "asset_type": record.asset_type,
        }
        if record.asset_type == "image":
            images.append(entry)
        elif record.asset_type == "interactive":
            interactive.append(entry)
        elif record.asset_type == "dashboard" and dashboard_url is None:
            dashboard_url = entry["url"]
    return {
        "project_id": project_id,
        "images": images,
        "interactive_charts": interactive,
        "interactive_dashboard": dashboard_url,
    }


@router.get("/projects/{project_id}/assets")
def list_project_assets(project_id: int, db: Session = Depends(get_db)):
    """Expose the current project's Allure chart assets."""
    return _list_project_visualizations(project_id, db)


def _project_asset_candidate(project, record):
    project_root = _project_root(project).resolve()
    candidate = (project_root / record.relative_path).resolve()
    if not str(candidate).startswith(str(project_root)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not candidate.exists() or not candidate.is_file():
        raise HTTPException(status_code=404, detail="Visualization file not found")
    return candidate


@router.get("/projects/{project_id}/assets/{asset_path:path}")
def get_project_asset(project_id: int, asset_path: str, db: Session = Depends(get_db)):
    """Serve an Allure chart asset that belongs to a specific project."""
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail=f"Project with id '{project_id}' not found")

    resolved_candidate = None
    media_type = "application/octet-stream"

    if asset_path.isdigit():
        record = (
            db.query(ProjectAllureChart)
            .filter(
                ProjectAllureChart.id == int(asset_path),
                ProjectAllureChart.project_id == project_id,
            )
            .first()
        )

        if not record:
            raise HTTPException(status_code=404, detail="Visualization not found")
        resolved_candidate = _project_asset_candidate(project, record)
        media_type = record.media_type or media_type
    else:
        charts_dir = (_project_root(project) / "generated_runs" / "src" / "allure_charts").resolve()
        normalized_path = asset_path.lstrip("/")
        assets_prefix = "assets/"
        while normalized_path.startswith(assets_prefix):
            normalized_path = normalized_path[len(assets_prefix):]
        candidate = (charts_dir / normalized_path).resolve()
        if not str(candidate).startswith(str(charts_dir)):
            raise HTTPException(status_code=403, detail="Forbidden")
        if not candidate.exists() or not candidate.is_file():
            raise HTTPException(status_code=404, detail="Visualization file not found")
        resolved_candidate = candidate
        media_type_guess, _ = mimetypes.guess_type(str(candidate))
        if media_type_guess:
            media_type = media_type_guess

    return FileResponse(resolved_candidate, media_type=media_type)


@router.get("/assets/{image_name}")
def get_visualization_asset(image_name: str):
    """Serve the raw image file for the visualizer output."""
    _ensure_visualizer_dir()
    candidate = (VISUALIZER_DIR / image_name).resolve()
    if not str(candidate).startswith(str(VISUALIZER_DIR_RESOLVED)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not candidate.exists() or not candidate.is_file():
        raise HTTPException(status_code=404, detail="Visualization not found")
    if candidate.suffix.lower() not in ALLOWED_ASSET_EXTENSIONS:
        raise HTTPException(status_code=403, detail="Visualization type not allowed")

    media_type, _ = mimetypes.guess_type(str(candidate))
    return FileResponse(candidate, media_type=media_type or "application/octet-stream")


@router.get("/dashboard")
def get_interactive_dashboard():
    """Serve the generated interactive HTML dashboard if available."""
    _ensure_visualizer_dir()
    dashboard = _dashboard_path()
    if not str(dashboard).startswith(str(VISUALIZER_DIR_RESOLVED)):
        raise HTTPException(status_code=403, detail="Forbidden")
    if not dashboard.exists() or not dashboard.is_file():
        raise HTTPException(status_code=404, detail="Interactive dashboard not found")
    return FileResponse(dashboard, media_type="text/html")
