from playwright.sync_api import sync_playwright

from pages.customer_page_methods import *

from pages.dashboard_page_methods import *

def test_positive_add_new_customer(page):
    page.goto("https://preview--bank-buddy-crm-react.lovable.app/")
    click_customers(page)
    verify_add_customer_visible(page)
    click_add_customer(page)
    verify_full_name_visible(page)
    enter_full_name(page, "John Doe")
    verify_email_visible(page)
    enter_email(page, "john.doe@example.com")
    verify_phone_number_visible(page)
    enter_phone_number(page, "1234567890")
    verify_select_account_type_visible(page)
    select_select_account_type(page, "Standard")
    verify_address_visible(page)
    enter_address(page, "123 Main St, Anytown, USA")
    verify_occupation_visible(page)
    enter_occupation(page, "Software Engineer")
    verify_annual_income_visible(page)
    enter_annual_income(page, "75000")
    verify_initial_deposit_visible(page)
    enter_initial_deposit(page, "1000")
    click_add_customer(page)
    enter_search_customers(page, "John Doe")

def test_negative_add_new_customer(page):
    page.goto("https://preview--bank-buddy-crm-react.lovable.app/")
    click_customers(page)
    verify_add_customer_visible(page)
    click_add_customer(page)
    verify_full_name_visible(page)
    enter_full_name(page, "John Doe")
    verify_email_visible(page)
    enter_email(page, "john.doe@example")
    verify_phone_number_visible(page)
    enter_phone_number(page, "1234567890")
    verify_select_account_type_visible(page)
    select_select_account_type(page, "Standard")
    verify_address_visible(page)
    enter_address(page, "123 Main St, Anytown, USA")
    verify_occupation_visible(page)
    enter_occupation(page, "Software Engineer")
    verify_annual_income_visible(page)
    enter_annual_income(page, "75000")
    verify_initial_deposit_visible(page)
    enter_initial_deposit(page, "1000")
    click_add_customer(page)

def test_edge_add_new_customer(page):
    page.goto("https://preview--bank-buddy-crm-react.lovable.app/")
    click_customers(page)
    verify_add_customer_visible(page)
    click_add_customer(page)
    verify_full_name_visible(page)
    enter_full_name(page, "J" * 256)
    verify_email_visible(page)
    enter_email(page, "john.doe@example.com")
    verify_phone_number_visible(page)
    enter_phone_number(page, "1234567890")
    verify_select_account_type_visible(page)
    select_select_account_type(page, "Standard")
    verify_address_visible(page)
    enter_address(page, "123 Main St, Anytown, USA")
    verify_occupation_visible(page)
    enter_occupation(page, "Software Engineer")
    verify_annual_income_visible(page)
    enter_annual_income(page, "75000")
    verify_initial_deposit_visible(page)
    enter_initial_deposit(page, "1000")
    click_add_customer(page)