# Auto-generated UI runner
import sys
from pathlib import Path as _Path
# Ensure generated_runs/src is on sys.path so 'from pages.*' imports work when running
# this script from the repository root or the backend folder.
_ROOT = _Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))
from playwright.sync_api import sync_playwright
import json
from pathlib import Path
from pages.bank_add_customer_page_methods import *
from pages.bank_customer_page_methods import *
from pages.bank_dashboard_page_methods import *
from pages.contact1_page_methods import *
from pages.contact2_page_methods import *
from pages.contact3_page_methods import *
from pages.contact_page_methods import *
from pages.dashbord_page_methods import *
from pages.detail2_page_methods import *
from pages.detail_page_methods import *
from pages.sandes_page_methods import *
from lib.smart_ai import patch_page_with_smartai
def run_positive_contact_creation():
    import time
    import os
    from pathlib import Path as _Path
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False, slow_mo=300)

        try:
            context = browser.new_context(storage_state="C:\\Users\\rswap\\OneDrive\\Desktop\\ai\\testify-automator-ai\\backend\\storage\\cookies.json")
            page = context.new_page()
            print(f"[ui_runner] Restored storage_state from provided path")
        except Exception as e:
            print(f"[ui_runner] Failed to restore provided storage_state: {e}")
            context = browser.new_context()
            page = context.new_page()

        # Patch SmartAI
        metadata_path = Path(__file__).parent.parent / "metadata" / "after_enrichment.json"
        with open(metadata_path, "r") as f:
            actual_metadata = json.load(f)
        patch_page_with_smartai(page, actual_metadata)
        page.goto("https://thdynamics365sandbox.crm4.dynamics.com/main.aspx")
        click_customer_service(page)
        click_contacts(page)
        click_new(page)
        select_salutation(page, "Mr.")
        assert_select_salutation(page, "Mr.")
        enter_first_name(page, "Jamie")
        assert_enter_first_name(page, "Jamie")
        enter_last_name(page, "Rivera")
        assert_enter_last_name(page, "Rivera")
        enter_job_title(page, "Support Analyst")
        assert_enter_job_title(page, "Support Analyst")
        enter_account_name(page, "akash")
        assert_enter_account_name(page, "akash")
        select_role(page, "Employee")
        assert_select_role(page, "Employee")
        enter_reports_to(page, "govind n")
        assert_enter_reports_to(page, "govind n")
        enter_department(page, "Customer Service")
        assert_enter_department(page, "Customer Service")
        select_primary_time_zone(page, "(GMT-05:00) Haiti")
        assert_select_primary_time_zone(page, "(GMT-05:00) Haiti")
        enter_email(page, "jamie.rivera@example.com")
        assert_enter_email(page, "jamie.rivera@example.com")
        enter_business_phone(page, "+91 40 5555 0188")
        assert_enter_business_phone(page, "+91 40 5555 0188")
        enter_mobile_phone(page, "+91 40 5555 0123")
        assert_enter_mobile_phone(page, "+91 40 5555 0123")
        enter_fax(page, "+91 40 5555 0199")
        assert_enter_fax(page, "+91 40 5555 0199")
        select_lead_source(page, "Web")
        assert_select_lead_source(page, "Web")
        select_preferred_method_of_contact(page, "Email")
        assert_select_preferred_method_of_contact(page, "Email")
        enter_hobbies_and_interests(page, "Hiking; Reading")
        assert_enter_hobbies_and_interests(page, "Hiking; Reading")
        enter_assistant(page, "Casey Morgan")
        assert_enter_assistant(page, "Casey Morgan")
        enter_assistant_phone(page, "+91 40 5555 0147")
        assert_enter_assistant_phone(page, "+91 40 5555 0147")
        enter_address_1_street_1(page, "12 Hitech City Rd")
        assert_enter_address_1_street_1(page, "12 Hitech City Rd")
        enter_address_1_city(page, "Hyderabad")
        assert_enter_address_1_city(page, "Hyderabad")
        enter_address_1_state_province(page, "Telangana")
        assert_enter_address_1_state_province(page, "Telangana")
        enter_address_1_country_region(page, "India")
        assert_enter_address_1_country_region(page, "India")
        enter_address_1_zip_postal_code(page, "500081")
        assert_enter_address_1_zip_postal_code(page, "500081")
        enter_address_1_phone(page, "+91 40 5555 0100")
        assert_enter_address_1_phone(page, "+91 40 5555 0100")
        enter_address_2_street_1(page, "44 MG Road")
        assert_enter_address_2_street_1(page, "44 MG Road")
        enter_address_2_city(page, "Bengaluru")
        assert_enter_address_2_city(page, "Bengaluru")
        enter_address_2_state_province(page, "Karnataka")
        assert_enter_address_2_state_province(page, "Karnataka")
        enter_address_2_country_region(page, "India")
        assert_enter_address_2_country_region(page, "India")
        enter_address_2_zip_postal_code(page, "560001")
        assert_enter_address_2_zip_postal_code(page, "560001")
        enter_address_2_phone(page, "+91 80 5555 0107")
        assert_enter_address_2_phone(page, "+91 80 5555 0107")
        click_details(page)
        select_gender(page, "Male")
        assert_select_gender(page, "Male")
        select_marital_status(page, "Married")
        assert_select_marital_status(page, "Married")
        enter_spouse_partner_name(page, "Alex Rivera")
        assert_enter_spouse_partner_name(page, "Alex Rivera")
        enter_credit_limit(page, "100000")
        assert_enter_credit_limit(page, "100000")
        select_credit_hold(page, "No")
        assert_select_credit_hold(page, "No")
        select_payment_terms(page, "Net 30")
        assert_select_payment_terms(page, "Net 30")
        select_shipping_method(page, "DHL")
        assert_select_shipping_method(page, "DHL")
        select_freight_terms(page, "FOB")
        assert_select_freight_terms(page, "FOB")
        select_originating_lead(page, "Arjun A")
        assert_select_originating_lead(page, "Arjun A")
        select_marketing_materials(page, "Send")
        assert_select_marketing_materials(page, "Send")
        click_save_close(page)
        time.sleep(3)
        browser.close()

def run_negative_contact_creation():
    import time
    import os
    from pathlib import Path as _Path
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False, slow_mo=300)

        try:
            context = browser.new_context(storage_state="C:\\Users\\rswap\\OneDrive\\Desktop\\ai\\testify-automator-ai\\backend\\storage\\cookies.json")
            page = context.new_page()
            print(f"[ui_runner] Restored storage_state from provided path")
        except Exception as e:
            print(f"[ui_runner] Failed to restore provided storage_state: {e}")
            context = browser.new_context()
            page = context.new_page()

        # Patch SmartAI
        metadata_path = Path(__file__).parent.parent / "metadata" / "after_enrichment.json"
        with open(metadata_path, "r") as f:
            actual_metadata = json.load(f)
        patch_page_with_smartai(page, actual_metadata)
        page.goto("https://thdynamics365sandbox.crm4.dynamics.com/main.aspx")
        click_customer_service(page)
        click_contacts(page)
        click_new(page)
        select_salutation(page, "Mr.")
        assert_select_salutation(page, "Mr.")
        enter_first_name(page, "")  # Missing first name
        enter_last_name(page, "Rivera")
        assert_enter_last_name(page, "Rivera")
        enter_job_title(page, "Support Analyst")
        assert_enter_job_title(page, "Support Analyst")
        enter_account_name(page, "akash")
        assert_enter_account_name(page, "akash")
        select_role(page, "Employee")
        assert_select_role(page, "Employee")
        enter_reports_to(page, "govind n")
        assert_enter_reports_to(page, "govind n")
        enter_department(page, "Customer Service")
        assert_enter_department(page, "Customer Service")
        select_primary_time_zone(page, "(GMT-05:00) Haiti")
        assert_select_primary_time_zone(page, "(GMT-05:00) Haiti")
        enter_email(page, "jamie.rivera@example.com")
        assert_enter_email(page, "jamie.rivera@example.com")
        enter_business_phone(page, "+91 40 5555 0188")
        assert_enter_business_phone(page, "+91 40 5555 0188")
        enter_mobile_phone(page, "+91 40 5555 0123")
        assert_enter_mobile_phone(page, "+91 40 5555 0123")
        enter_fax(page, "+91 40 5555 0199")
        assert_enter_fax(page, "+91 40 5555 0199")
        select_lead_source(page, "Web")
        assert_select_lead_source(page, "Web")
        select_preferred_method_of_contact(page, "Email")
        assert_select_preferred_method_of_contact(page, "Email")
        enter_hobbies_and_interests(page, "Hiking; Reading")
        assert_enter_hobbies_and_interests(page, "Hiking; Reading")
        enter_assistant(page, "Casey Morgan")
        assert_enter_assistant(page, "Casey Morgan")
        enter_assistant_phone(page, "+91 40 5555 0147")
        assert_enter_assistant_phone(page, "+91 40 5555 0147")
        enter_address_1_street_1(page, "12 Hitech City Rd")
        assert_enter_address_1_street_1(page, "12 Hitech City Rd")
        enter_address_1_city(page, "Hyderabad")
        assert_enter_address_1_city(page, "Hyderabad")
        enter_address_1_state_province(page, "Telangana")
        assert_enter_address_1_state_province(page, "Telangana")
        enter_address_1_country_region(page, "India")
        assert_enter_address_1_country_region(page, "India")
        enter_address_1_zip_postal_code(page, "500081")
        assert_enter_address_1_zip_postal_code(page, "500081")
        enter_address_1_phone(page, "+91 40 5555 0100")
        assert_enter_address_1_phone(page, "+91 40 5555 0100")
        enter_address_2_street_1(page, "44 MG Road")
        assert_enter_address_2_street_1(page, "44 MG Road")
        enter_address_2_city(page, "Bengaluru")
        assert_enter_address_2_city(page, "Bengaluru")
        enter_address_2_state_province(page, "Karnataka")
        assert_enter_address_2_state_province(page, "Karnataka")
        enter_address_2_country_region(page, "India")
        assert_enter_address_2_country_region(page, "India")
        enter_address_2_zip_postal_code(page, "560001")
        assert_enter_address_2_zip_postal_code(page, "560001")
        enter_address_2_phone(page, "+91 80 5555 0107")
        assert_enter_address_2_phone(page, "+91 80 5555 0107")
        click_details(page)
        select_gender(page, "Male")
        assert_select_gender(page, "Male")
        select_marital_status(page, "Married")
        assert_select_marital_status(page, "Married")
        enter_spouse_partner_name(page, "Alex Rivera")
        assert_enter_spouse_partner_name(page, "Alex Rivera")
        enter_credit_limit(page, "100000")
        assert_enter_credit_limit(page, "100000")
        select_credit_hold(page, "No")
        assert_select_credit_hold(page, "No")
        select_payment_terms(page, "Net 30")
        assert_select_payment_terms(page, "Net 30")
        select_shipping_method(page, "DHL")
        assert_select_shipping_method(page, "DHL")
        select_freight_terms(page, "FOB")
        assert_select_freight_terms(page, "FOB")
        select_originating_lead(page, "Arjun A")
        assert_select_originating_lead(page, "Arjun A")
        select_marketing_materials(page, "Send")
        assert_select_marketing_materials(page, "Send")
        click_save_close(page)
        time.sleep(3)
        browser.close()

def run_edge_contact_creation():
    import time
    import os
    from pathlib import Path as _Path
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False, slow_mo=300)

        try:
            context = browser.new_context(storage_state="C:\\Users\\rswap\\OneDrive\\Desktop\\ai\\testify-automator-ai\\backend\\storage\\cookies.json")
            page = context.new_page()
            print(f"[ui_runner] Restored storage_state from provided path")
        except Exception as e:
            print(f"[ui_runner] Failed to restore provided storage_state: {e}")
            context = browser.new_context()
            page = context.new_page()

        # Patch SmartAI
        metadata_path = Path(__file__).parent.parent / "metadata" / "after_enrichment.json"
        with open(metadata_path, "r") as f:
            actual_metadata = json.load(f)
        patch_page_with_smartai(page, actual_metadata)
        page.goto("https://thdynamics365sandbox.crm4.dynamics.com/main.aspx")
        click_customer_service(page)
        click_contacts(page)
        click_new(page)
        select_salutation(page, "Mr.")
        assert_select_salutation(page, "Mr.")
        enter_first_name(page, "J" * 256)  # Very long first name
        enter_last_name(page, "Rivera")
        assert_enter_last_name(page, "Rivera")
        enter_job_title(page, "Support Analyst")
        assert_enter_job_title(page, "Support Analyst")
        enter_account_name(page, "akash")
        assert_enter_account_name(page, "akash")
        select_role(page, "Employee")
        assert_select_role(page, "Employee")
        enter_reports_to(page, "govind n")
        assert_enter_reports_to(page, "govind n")
        enter_department(page, "Customer Service")
        assert_enter_department(page, "Customer Service")
        select_primary_time_zone(page, "(GMT-05:00) Haiti")
        assert_select_primary_time_zone(page, "(GMT-05:00) Haiti")
        enter_email(page, "jamie.rivera@example.com")
        assert_enter_email(page, "jamie.rivera@example.com")
        enter_business_phone(page, "+91 40 5555 0188")
        assert_enter_business_phone(page, "+91 40 5555 0188")
        enter_mobile_phone(page, "+91 40 5555 0123")
        assert_enter_mobile_phone(page, "+91 40 5555 0123")
        enter_fax(page, "+91 40 5555 0199")
        assert_enter_fax(page, "+91 40 5555 0199")
        select_lead_source(page, "Web")
        assert_select_lead_source(page, "Web")
        select_preferred_method_of_contact(page, "Email")
        assert_select_preferred_method_of_contact(page, "Email")
        enter_hobbies_and_interests(page, "Hiking; Reading")
        assert_enter_hobbies_and_interests(page, "Hiking; Reading")
        enter_assistant(page, "Casey Morgan")
        assert_enter_assistant(page, "Casey Morgan")
        enter_assistant_phone(page, "+91 40 5555 0147")
        assert_enter_assistant_phone(page, "+91 40 5555 0147")
        enter_address_1_street_1(page, "12 Hitech City Rd")
        assert_enter_address_1_street_1(page, "12 Hitech City Rd")
        enter_address_1_city(page, "Hyderabad")
        assert_enter_address_1_city(page, "Hyderabad")
        enter_address_1_state_province(page, "Telangana")
        assert_enter_address_1_state_province(page, "Telangana")
        enter_address_1_country_region(page, "India")
        assert_enter_address_1_country_region(page, "India")
        enter_address_1_zip_postal_code(page, "500081")
        assert_enter_address_1_zip_postal_code(page, "500081")
        enter_address_1_phone(page, "+91 40 5555 0100")
        assert_enter_address_1_phone(page, "+91 40 5555 0100")
        enter_address_2_street_1(page, "44 MG Road")
        assert_enter_address_2_street_1(page, "44 MG Road")
        enter_address_2_city(page, "Bengaluru")
        assert_enter_address_2_city(page, "Bengaluru")
        enter_address_2_state_province(page, "Karnataka")
        assert_enter_address_2_state_province(page, "Karnataka")
        enter_address_2_country_region(page, "India")
        assert_enter_address_2_country_region(page, "India")
        enter_address_2_zip_postal_code(page, "560001")
        assert_enter_address_2_zip_postal_code(page, "560001")
        enter_address_2_phone(page, "+91 80 5555 0107")
        assert_enter_address_2_phone(page, "+91 80 5555 0107")
        click_details(page)
        select_gender(page, "Male")
        assert_select_gender(page, "Male")
        select_marital_status(page, "Married")
        assert_select_marital_status(page, "Married")
        enter_spouse_partner_name(page, "Alex Rivera")
        assert_enter_spouse_partner_name(page, "Alex Rivera")
        enter_credit_limit(page, "100000")
        assert_enter_credit_limit(page, "100000")
        select_credit_hold(page, "No")
        assert_select_credit_hold(page, "No")
        select_payment_terms(page, "Net 30")
        assert_select_payment_terms(page, "Net 30")
        select_shipping_method(page, "DHL")
        assert_select_shipping_method(page, "DHL")
        select_freight_terms(page, "FOB")
        assert_select_freight_terms(page, "FOB")
        select_originating_lead(page, "Arjun A")
        assert_select_originating_lead(page, "Arjun A")
        select_marketing_materials(page, "Send")
        assert_select_marketing_materials(page, "Send")
        click_save_close(page)
        time.sleep(3)
        browser.close()


if __name__ == '__main__':
    run_positive_contact_creation()
    run_negative_contact_creation()
    run_edge_contact_creation()
